### ISSUE TITLE
Question about configuring the Google Calendar integration

### ISSUE THREAD

**Issue by danionescu0** [veebch/hometime#10]
So if i understand correct for the Google Calendar intergration to work one needs to have:

- an event at the begining of the day
- an event at the end of the day
- zero or more events between ?

Have i understood correct? I am asking because i am want to write an instructable (tutoral) for the project

**Comment by veebch** [comment]
Correct. The idea is to encourage a calendar that describes the working day, Nothing in the calendar for the day means no work. Things in the calendar mean the day starts at the beginning of the first event, and ends at the end of the last event.

**Comment by danionescu0** [comment]
Done
