### ISSUE TITLE
Bar not working when Flip is true

### ISSUE THREAD

**Issue by danionescu0** [veebch/hometime#11]
I have tested the bar with Flip = True in config.py and it does not work

Logs:

MicroPython v1.20.0 on 2023-04-26; Raspberry Pi Pico W with RP2040
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
2023-06-30 08:34:58 [debug    / 153kB]   - got ip address
Connected to wifi, IP address 192.168.1.110
Entering application mode.
Rainbow!
Connected to WiFi
Turn off all LEDs
Grab time: https://timeapi.io/api/TimeZone/zone?timezone=Europe/Bucharest
Begin endless loop
Updating from Google Calendar
['2023-06-30T08:00:00+03:00', '2023-06-30T08:15:00+03:00', '2023-06-30T19:00:00+03:00', '2023-06-30T19:15:00+03:00']
['2023-06-30T08:00:00+03:00', '2023-06-30T08:15:00+03:00', '2023-06-30T19:00:00+03:00', '2023-06-30T19:15:00+03:00']
clockin: 8.0
Pour yourself a cup of ambition
Exception: bytearray index out of range
Turn off all LEDs

Connection lost (device reports readiness to read but returned no data (device disconnected or multiple access on port?))

Use Stop/Restart to reconnect.

Logs when its working (but with flip=False):

MicroPython v1.20.0 on 2023-04-26; Raspberry Pi Pico W with RP2040
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
2023-06-28 11:38:47 [debug    / 150kB]   - got ip address
Connected to wifi, IP address 192.168.1.110
Entering application mode.
Rainbow!
Connected to WiFi
Turn off all LEDs
Grab time: https://timeapi.io/api/TimeZone/zone?timezone=Europe/Bucharest
Begin endless loop
Updating from Google Calendar
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00']
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
Updating from Google Calendar
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00']
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5
['2023-06-19T08:30:00+03:00', '2023-06-19T09:30:00+03:00', '2023-06-19T21:30:00+03:00', '2023-06-19T21:35:00+03:00', '2023-06-27T21:30:00+03:00', '2023-06-27T21:45:00+03:00', '2023-06-28T08:30:00+03:00', '2023-06-28T09:00:00+03:00']
clockin: 8.5

**Comment by veebch** [comment]
Good catch....The flip code has been simplified and fixed....
