### ISSUE TITLE
Code problems

### ISSUE THREAD

**Issue by danionescu0** [veebch/hometime#12]
I think the latest fix has some issues with indentation :

```
    wdt = machine.WDT(timeout=8000)  # enable watchdog timer with a timeout of 8s
    while True:
while True:
```

Also i saw you removed some parameters from the "hourtoindex" function, but not everywhere, i thik that might also be an issue
`        index = hourtoindex(hour, clockin, clockout)`

**Comment by danionescu0** [comment]
Thanks a lot for the quick response! i'll test it soon and get back here:)
Is it ok if i create a tutorial for this project? of course i'll mention your repository and give the credit to you :)

**Comment by veebch** [comment]
Super..... Definitely OK to create a tutorial!

**Comment by danionescu0** [comment]
Still indentation problems i have a sintax error:
```
            except Exception as e:
                print('Exception:',e)
                off(np)
                time.sleep(1)
                machine.reset()
            except KeyboardInterrupt:
                off(np)
```

I've fixed that, but after it boots and shows the rainbow it stops working, and reboots from time to time

Entering application mode.
Rainbow!

Connection lost (device reports readiness to read but returned no data (device disconnected or multiple access on port?))

**Comment by veebch** [comment]
The watchdog timer means that it needs to be reconnected for each run. If there is a bug causing the crash, it will reboot. Also, if you're debugging, the device needs to be reset 

https://docs.micropython.org/en/latest/library/machine.WDT.html

**Comment by danionescu0** [comment]
The code hangs after is making a request to get the time:

Turn off all LEDs
Grab time: https://timeapi.io/api/TimeZone/zone?timezone=Europe/Bucharest

**Comment by danionescu0** [comment]
Strange because the requests is valid if i ope it in the browser

**Comment by danionescu0** [comment]
Ok fixed it , was wifi issues, now i have this:

>>> %Run -c $EDITOR_CONTENT
2023-06-30 13:13:21 [debug    / 151kB]   - connecting
2023-06-30 13:13:24 [debug    / 149kB]   - connecting
Connected to wifi, IP address 192.168.1.110
Entering application mode.
Rainbow!
Connected to WiFi
Turn off all LEDs
Grab time: https://timeapi.io/api/TimeZone/zone?timezone=Europe/Bucharest
Begin endless loop
Updating from Google Calendar
['2023-06-30T08:00:00+03:00', '2023-06-30T08:15:00+03:00', '2023-06-30T19:00:00+03:00', '2023-06-30T19:04:00+03:00', '2023-06-30T14:00:00+03:00', '2023-06-30T15:00:00+03:00']
['2023-06-30T08:00:00+03:00', '2023-06-30T08:15:00+03:00', '2023-06-30T14:00:00+03:00', '2023-06-30T15:00:00+03:00', '2023-06-30T19:00:00+03:00', '2023-06-30T19:04:00+03:00']
clockin: 8.0
True 8.0 19.06667 13.23
Pour yourself a cup of ambition
Exception: function takes 4 positional arguments but 2 were given
Turn off all LEDs

Connection lost (device reports readiness to read but returned no data (device disconnected or multiple access on port?))

**Comment by danionescu0** [comment]
Now the flip=True works, but still one issue remains, the code reboots from time to time (a few minutes apart)
True 8.0 19.06667 13.86306
Pour yourself a cup of ambition
Flipped
True 8.0 19.06667 13.86333
Pour yourself a cup of ambition
Flipped
True 8.0 19.06667 13.86361
Pour yourself a cup of ambition
Flipped
Updating from Google Calendar

Connection lost (device reports readiness to read but returned no data (device disconnected or multiple access on port?))

**Comment by danionescu0** [comment]
Do you have suggestions about how can i debug this ?

**Comment by veebch** [comment]
Try commenting out the watchdog timer (wdt) lines. It could be that the connection takes longer than the timeout value (8388 ms is the maximum)

**Comment by danionescu0** [comment]
Yes, it was the timer? Do you suggest setting a higher value or removing it ?

**Comment by veebch** [comment]
It's at the maximum but more feed statements would help it not get tripped. It seems that a google API call taking 8 seconds is unusual, so I'd try it with the extra feed statements I put in and see if they fixed it. Failing that, running the api call as a thread and topping up the timer while you wait might also work.

There are lots of ways to do it, but the watchdog timer thing is a neat way to manage crashes.

**Comment by veebch** [comment]
And I took them out :) They were messing with the wifi connection on the occasions that the router was slow to respond or the Access point was waiting for input
