### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by danionescu0** [veebch/hometime#16]
I've created the following tutorial, if you like you can include it on your page: 
https://medium.com/@ionescu.dan84/workday-progressbar-with-google-calendar-integration-b266aabd32a8

**Comment by veebch** [comment]
Looks great. I'll add it to the readme. Nice photos!

**Comment by danionescu0** [comment]
Thank you! you did a great work with this project

**Comment by veebch** [comment]
The timelapse is really good. Reddit is a good place to show off your fine work :)

**Comment by danionescu0** [comment]
Thans for the idee! i've posted it :)
