### ISSUE TITLE
Hometime

### ISSUE THREAD

**Issue by H4K0N42** [veebch/hometime#2]
Is it possible to make the day longer for a spesific time in the calendar, because school doesnt end always at 13:00

**Comment by veebch** [comment]
Sure, that should be easy, as it gets the day of the week from the time server too. Have a try at adding it, if you need a hand, let me know :)

**Comment by H4K0N42** [comment]
I have 2 Questions:

1. Where should this code go, so it can run at every day once?
2. Is clockout = 13.5; 13:30 or 13:50?

```
import datetime

def dayofweek():
    global clockin, clockout
    weekday = datetime.datetime.today().weekday()
    if weekday == 0: print("Monday");       clockin = 7.45; clockout = 13.5
    if weekday == 1: print("Tuesday");      clockin = 7.45; clockout = 12.1
    if weekday == 2: print("Wednesday");    clockin = 7.45; clockout = 12.1
    if weekday == 3: print("Thursday");     clockin = 7.45; clockout = 13.5
    if weekday == 4: print("Friday");       clockin = 7.45; clockout = 13.0
    if weekday == 5: print("Saturday");     clockin = 0.00; clockout = 00.0
    if weekday == 6: print("Sunday");       clockin = 0.00; clockout = 00.0

dayofweek()
```

**Comment by veebch** [comment]
13.5 == 13.5 hours == 13:30

**Comment by veebch** [comment]
(I've put a json parameter for the clockin/clockout on each day of the week)

**Comment by H4K0N42** [comment]
Sorry for wasting your time again, but can you please structure / write that ujson file with this events for every day:

08:30 - 08:35
09:20 - 09:35
10:20 - 10:25
11:10 - 11:25
12:10 - 12:15
13:00 - 13:05

Could you store that file directly on the pico?

Thank you so mutch
-H4K0N

**Comment by veebch** [comment]
I don't have time to do that right now, but I've left a comment in main.py in the place that you'd add any hardcoded events :)
