### ISSUE TITLE
[BUG] Events not triggert

### ISSUE THREAD

**Issue by H4K0N42** [veebch/hometime#23]
When you use reocurring events, the eventbool doesnt get set to true, when clockout should trigger, the pico doesnt reboot and the LEDs dont turn off.

**Comment by veebch** [comment]
Do you have an example of the Thonny console output when this happens?

**Comment by H4K0N42** [comment]
Not yet, I send you the output, when im home

**Comment by H4K0N42** [comment]
![image](https://github.com/veebch/hometime/assets/78751562/3a405983-20c1-4801-acf7-4eaf3ddc5a5a)


I found the issue, when google updates while an event should trigger or the day ends, it doesn't get triggert, can you make the google update async? I do not know how to use async on micropython.

**Comment by veebch** [comment]
I think that making async work properly would require a decent amount of changes to the logic. Currently just making it async (or a thread) might lead to funky stuff happening while it was processing the appointment times. The quick and dirty solution is just to reduce the frequency with which google is checked.

**Comment by H4K0N42** [comment]
I just fixed issue the same way, when you merge my pull request for more animations please change the 30 sec back to 60 sec like you did before.

**Comment by H4K0N42** [comment]
The problem is there again, sometimes events doesnt trigger, i don't know why. The log is just "Working=True ..."

**Comment by veebch** [comment]
Do you have the thonny output from a time it happens?

**Comment by H4K0N42** [comment]
There is no special output, its just Working=True, clockin=7.75, clockout=18.33, hoursin=17.73 ...
Also when you delete a reocurring event only for one day (not permanent) it still shows up on the Bar

**Comment by H4K0N42** [comment]
![image](https://github.com/veebch/hometime/assets/78751562/41b0d068-7e98-4905-af06-54f5f8f48c35)
from the google api, I cant find any diffrences there ...

**Comment by veebch** [comment]
The only real difference that I see is the duration.

This is the point where it would make sense to think about an improved logic that has some kind of callback to make sure that events are flagged at the exact time you want.
