### ISSUE TITLE
Event date parsing gives error for zones west of Z

### ISSUE THREAD

**Issue by gns-jdaniel** [veebch/hometime#3]
Awesome project!

One problem I noted was that on line 115 in timetohour(time_string):

`  # Extract the time portion from the string
    time_part = time_string.split("T")[1].split("+")[0]`

gives an error because my time zone is - not + from Z:

`Connected to WiFi
Turn off all LEDs
Grab time: https://timeapi.io/api/TimeZone/zone?timeZone=America/Vancouver
(2023, 5, 16, 21, 43, 13, 1, 136)
Begin endless loop
https://www.googleapis.com/calendar/v3/calendars/mycalendarurl%40group.calendar.google.com/events?timeMin=2023-05-16T00:00:00-07:00&timeMax=2023-05-16T23:59:59-07:00&key=MyKeyGoesHere
['2023-05-16T22:00:00-07:00', '2023-05-16T22:45:00-07:00', '2023-05-16T21:15:00-07:00', '2023-05-16T22:00:00-07:00']
too many values to unpack (expected 3)
Turn off all LEDs
`

So I changed the "+" to a "-" in the time_part calculation, and it no longer errored-out. I realize Micropython doesn't have the full datetime, and your elegant workaround might need some tweaking or documenting.

One other thing is that the get_today_appointment_times function (line 45) uses Z rather than local times, so my -07:00 from Z would often omit events and offset the ones that still fell within the workday window:

`    url = f"https://www.googleapis.com/calendar/v3/calendars/{calendar_id}/events"
    url += f"?timeMin={date}T00:00:00Z&timeMax={date}T23:59:59Z&key={api_key}"
`

Again, with no datetime, it makes dealing with time zones a pain. My workaround was to change the Z to my Z offset:

`    url = f"https://www.googleapis.com/calendar/v3/calendars/{calendar_id}/events"
    url += f"?timeMin={date}T00:00:00-07:00&timeMax={date}T23:59:59-07:00&key={api_key}"
`

But that's cheating! 

Thanks for posting such great ideas - my 9-year-old is building sploosh for her school's hydroponics lab.

**Comment by veebch** [comment]
It looks like switching to another api will allow you to get the offset. It can also may be made to use the IP rather than a hard-coded region, but I picture it getting screwy with vpns on some setups. 

Anyway, it is now on the to-do list. And tell your daughter that a photo of her finished project would be greatly appreciated :)
