### ISSUE TITLE
How to add API Key on google calendar

### ISSUE THREAD

**Issue by danionescu0** [veebch/hometime#4]
Hi there. Fist of all i like your project it looks great! I've already replicated part of it:)
But for the part of the integration with Google Calendar API i'm having some issues. 
Now that the code has migrated from OAUTH and a local server to directly accessing the Google Calendar API i can't get it working because in My Google Calendar API / Credentials section i only have two options: OAuth 2.0 Client IDs and Service Accounts.

Is this a coutry based limitation, or maybe i'm not looking in the right section of the configuration?

thanks!

**Comment by veebch** [comment]
Thanks, glad you like it. As for the Calendar bit....So much for simplicity :) 
 
Even though I made my calendar public (by publishing to web) I needed an API key or Google would bounce me. 

One thing  I had to do was set my API key to unrestricted access. Maybe that helps?

**Comment by danionescu0** [comment]
Thank you for the very quick response, i've also made a test calendar public. But i don't know how to create that API Key yet. I thought it was simple :)

**Comment by veebch** [comment]
This page?

https://console.cloud.google.com/apis/credentials

**Comment by veebch** [comment]
The API key needs to replace the bit in the quotes on the code. That should do it :)

**Comment by danionescu0** [comment]
Shell replaces my variables defined before, but still the project seems not found, maybe there is more on the configuration side, i need to dig into that

**Comment by danionescu0** [comment]
Ok got it working, i should have use the calendar in (in form of  an email address), my calendar was not primary. Thanks for your help, this resource really helped a lot https://console.cloud.google.com/apis/credentials

**Comment by veebch** [comment]
Excellent. Closing, but I'll add the link to the readme....
