### ISSUE TITLE
GUI improvment

### ISSUE THREAD

**Issue by danionescu0** [veebch/hometime#5]
What do you think of a simple GUI for setting parameters like 9-5 intervals each day?

One way it could work would be:
- use presses a phisical button connected to a GPIO PIN
- the script reboots and sets the board as AP mode, you  can connect to it's WIFI with a predefined password
- the user navigates to it's IP / settings page 
- WIFI credentials are settable
- 9-5 intervals are also settable
- A save button is available, when pressed the board the server saves the settings, and reboots in normal operations mode

**Comment by veebch** [comment]
It's a tricky one, the Google UI is pretty ideal for the calendar. Maybe the work hours should be stored in there somehow.

**Comment by veebch** [comment]
The google calendar now determines the start and end of the working day, so there is less of a need to tinker with the physical device after setup.  An AP might still be useful to configure WIFI settings and if there was an easier way to link to the calendar, it could be really useful. 

Closing for now, but I'll keep trying to think of a more elegant way to link to a calendar
