### ISSUE TITLE
Improvement for WIFI credentials

### ISSUE THREAD

**Issue by danionescu0** [veebch/hometime#7]
I want to to an improvement with setting up WIFI credentials
If a pushbutton is pressed the board could enter in AP mode and offer a simple page where WIFI credentials are set, then getback on normal mode

What do you think about it? I could try writing the code :)

**Comment by danionescu0** [comment]
Ok cool. Please keep the ticket open and i'll work on it when i have free time.

**Comment by danionescu0** [comment]
Ok, so i've tested the repo you suggested 192.168.1.110, it works fine. But to use the example there i would need some code copy pasting into this project. 
Another alternative is develop a similar functionality based on a more known "framework" : https://github.com/pimoroni/phew
Which alternative would you prefer? 
Regardless of the library i propose using a pushbutton, because with this alternative you can always reconfigure the wifi by pressing the button. If we rely on the presence of the wifi  config file you could just configure the first time

**Comment by veebch** [comment]
It's a question I've thought about, phewap is clever in that the AP reappears any time the wifi credentials stop working (or the wifi it is used to is no longer there)

The people making a progress bar are all savvy enough to get to the files on the pico if they need to, so I think no button, just the phewap code.

**Comment by danionescu0** [comment]
I've forked the repository and made the changes and tested locally the setup (without google calendar integration), seems to work, before submitting the PR if you like to take a look and they are here : https://github.com/danionescu0/hometime/tree/issue-7-wificonfig

**Comment by veebch** [comment]
I;ve skimmed through it and it looks good, I'll do a quick test with google calendar and merge it.

**Comment by danionescu0** [comment]
Ok thanks for accepting my update! I have an unresolved issue though, i've used Thonny editor to install the "phew" library used for the web server. Should i update the documentation to add details on how to do that? or do you suggest an alternative ?

**Comment by veebch** [comment]
I've added phew to the repo....I'll update the readme as soon as I get a chance

**Comment by danionescu0** [comment]
Ok great, i'll close this issue then
